# Build settings
markdown: kramdown
highlighter: rouge
exclude: [.gitignore, _site, README.markdown, package.json, grunt.js, Gruntfile.coffee, node_modules, .git, .vagrant, less]
url: https://moonsault.co
permalink: /:year/:month/:day/:title
description: "Software Consulting in Denver, CO. We focus on rapid, high quality delivery and excellent communication."
gems: [jekyll-paginate]
kramdown:
  input: GFM
  syntax_highlighter: rouge