# Build settings
markdown: kramdown
highlighter: rouge
exclude: [.gitignore, _site, README.markdown, package.json, grunt.js, Gruntfile.coffee, node_modules, .git, .vagrant, less]
paginate: 20
url: https://moonsault.co
gems: [jekyll-paginate]
kramdown:
  input: GFM
  syntax_highlighter: rouge