# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"
exclude: [.gitignore, _site, README.markdown, package.json, grunt.js, Gruntfile.coffee, node_modules, .git, .vagrant, less]
